name: Publish NPM Package

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger publishing from
  release:
    types: [created] # Trigger on new release creation

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required to checkout the code
      packages: write  # Required to publish to GitHub Packages (if applicable)
      id-token: write  # Required to publish to npmjs.org
    steps:
      - uses: actions/checkout@v4  # Checks out your code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Or the Node.js version you require
          registry-url: 'https://registry.npmjs.org/' # NPM Registry URL

      - name: Install dependencies
        run: npm install  # Installs dependencies

      - name: Build package
        run: npm run build  # Runs your build script from package.json

      # You may want to include a test step here if your package has tests
      # - name: Run tests
      #  run: npm test

      - name: Publish to NPM
        run: npm publish --access public  # Publish your package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_secret }} # NPM token from GitHub Secrets
